apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-auth
  template:
    metadata:
      labels:
        role: msvc-auth
    spec:
      containers:
      - name: msvc-auth
        image: leonespartano/auth:v1.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
          - name: LB_USUARIOS_URI
            valueFrom:
              configMapKeyRef:
                key: lb_usuarios_uri
                name: msvc-usuarios
              
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
spec:
  selector:
    role: msvc-auth
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  type: LoadBalancer
