apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-usuarios
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      containers:
      - image: leonespartano/usuarios:v1.1.2
        name: usuarios
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
          - name: LB_AUTH_ISSUER_URI
            valueFrom:
              configMapKeyRef:
                key: lb_auth_issuer_uri
                name: msvc-usuarios
          - name: LB_USUARIOS_URI
            valueFrom:
              configMapKeyRef:
                key: lb_usuarios_uri
                name: msvc-usuarios
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: msvc-usuarios
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: database
                name: msvc-usuarios
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: msvc-usuarios
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: msvc-usuarios
          - name: CURSOS_URL
            valueFrom:
              configMapKeyRef:
                key: curso_url
                name: msvc-usuarios
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health/readiness
        #     port: 8001
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 20
        #   timeoutSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: 8001
        #     scheme: HTTP
        #   initialDelaySeconds: 10
        #   periodSeconds: 30
        #   timeoutSeconds: 10
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "800Mi"
        #     cpu: "800m"
          # - name: SPRING_PROFILES_ACTIVE
          #   value: prod