apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-usuarios
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      containers:
      - image: leonespartano/usuarios:v1.1.2
        name: usuarios
        ports:
        - containerPort: 8001
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: msvc-usuarios
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: database
                name: msvc-usuarios
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: msvc-usuarios
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: msvc-usuarios
          - name: CURSOS_URL
            valueFrom:
              configMapKeyRef:
                key: curso_url
                name: msvc-usuarios
          - name: SPRING_PROFILES_ACTIVE
            value: kube