apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
      - name: postgres14
        image: postgres:14-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
            - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: sasa
          - name: POSTGRES_DB
            value: msvc_cursos
