server:
  port: ${PORT:8002}

spring:
  application:
    name: msvc-cursos
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5532}/${DB_DATABASE:msvc_cursos}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true


logging:
  level:
    org:
      hibernate:
        SQL: debug

#msvc:
#  usuarios:
#    url: ${USUARIOS_URL:msvc-usuarios:8001}
