server:
  port: ${PORT:8002}

spring:
  application:
    name: msvc-cursos
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres14:5432}/${DB_DATABASE:msvc_cursos}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

msvc:
  usuarios:
    url: ${USUARIOS_URL:msvc-usuarios:8001}