server:
  port: ${PORT:8001}
spring:
  application:
    name: msvc-usuarios
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql8:3306}/${DB_DATABASE:msvc_usuarios}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
  file:
    path: /app/logs

msvc:
  cursos:
    url: ${CURSOS_URL:msvc-cursos:8002}
