server:
  port: ${PORT:8001}
spring:
  application:
    name: msvc-usuarios
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3307}/${DB_DATABASE:msvc_usuarios}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
      client:
        registration:
          msvc-usuarios-client:
            provider: spring
            client-id: usuarios-client
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8001/authorized"
            scope: read
            client-name: msvc-usuarios-client
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000

logging:
  level:
    org:
      hibernate:
        SQL: debug
  file:
    path: /app/logs

#msvc:
#  cursos:
#    url: ${CURSOS_URL:msvc-cursos:8002}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true